<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="TYSS-Anjali" failures="2" tests="13" name="practice.testNG.InvoiceTest" time="122.737" errors="0" timestamp="2024-07-08T09:59:34 IST" skipped="10">
  <testcase classname="practice.testNG.InvoiceTest" name="invoiceWithContactTest" time="9.211"/>
  <system-out/>
  <testcase classname="practice.testNG.InvoiceTest" name="invoiceTest" time="9.159">
    <skipped/>
  </testcase> <!-- invoiceTest -->
  <system-out/>
  <testcase classname="practice.testNG.InvoiceTest" name="activateSim" time="10.373">
    <skipped/>
  </testcase> <!-- activateSim -->
  <system-out/>
  <testcase classname="practice.testNG.InvoiceTest" name="activateSim" time="9.387">
    <skipped/>
  </testcase> <!-- activateSim -->
  <system-out/>
  <testcase classname="practice.testNG.InvoiceTest" name="activateSim" time="10.451">
    <failure message="expected [Login] but found []" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Login] but found []
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at practice.testNG.InvoiceTest.activateSim(InvoiceTest.java:40)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- activateSim -->
  <system-out/>
  <testcase classname="practice.testNG.InvoiceTest" name="invoiceTest" time="9.031">
    <skipped/>
  </testcase> <!-- invoiceTest -->
  <system-out/>
  <testcase classname="practice.testNG.InvoiceTest" name="activateSim" time="9.296">
    <skipped/>
  </testcase> <!-- activateSim -->
  <system-out/>
  <testcase classname="practice.testNG.InvoiceTest" name="invoiceTest" time="9.324">
    <skipped/>
  </testcase> <!-- invoiceTest -->
  <system-out/>
  <testcase classname="practice.testNG.InvoiceTest" name="activateSim" time="9.299">
    <skipped/>
  </testcase> <!-- activateSim -->
  <system-out/>
  <testcase classname="practice.testNG.InvoiceTest" name="invoiceTest" time="9.318">
    <skipped/>
  </testcase> <!-- invoiceTest -->
  <system-out/>
  <testcase classname="practice.testNG.InvoiceTest" name="invoiceTest" time="9.232">
    <failure message="expected [Login] but found [Administrator - Home - vtiger CRM 5 - Commercial Open Source CRM]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Login] but found [Administrator - Home - vtiger CRM 5 - Commercial Open Source CRM]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at practice.testNG.InvoiceTest.invoiceTest(InvoiceTest.java:17)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- invoiceTest -->
  <system-out/>
  <testcase classname="practice.testNG.InvoiceTest" name="activateSim" time="9.555">
    <skipped/>
  </testcase> <!-- activateSim -->
  <system-out/>
  <testcase classname="practice.testNG.InvoiceTest" name="invoiceTest" time="9.101">
    <skipped/>
  </testcase> <!-- invoiceTest -->
  <system-out/>
</testsuite> <!-- practice.testNG.InvoiceTest -->
